### ISSUE TITLE
Set up Semantic Layer + Viz on Preset

### ISSUE THREAD

**Issue by wacko-professional** [wacko-professional/project-2-team-7-dec#4]

**Comment by lpadgett23** [comment]
The connection with Preset

**Comment by lpadgett23** [comment]
Could not get the databricks connection to load any table into the Preset workspace and our transformation stages were still ongoing. In the interest of time, decided to switch dashboard plan over to Databricks SQL.

**Comment by lpadgett23** [comment]
Issue closed and new issue for DB created
